apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

generatorOptions:
  disableNameSuffixHash: true

resources:
  - 00-namespace.yaml
  - 10-tempo-configmap.yaml
  - 20-tempo.yaml
  - 30-grafana-datasource.yaml
  - 40-grafana.yaml
  - 50-prometheus-configmap.yaml
  - 60-prometheus.yaml
  - 70-grafana-dashboards.yaml

configMapGenerator:
  - name: grafana-dashboards-otelcol
    files:
      - mode_dash.json=mode_dash.json


