apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-java-config
  namespace: demo-app
data:
  GLOWROOT_COLLECTOR: "172.16.240.127:8181"
  SERVER_PORT: "8080"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres.demo-app.svc.cluster.local:5432/appdb"
  SPRING_DATASOURCE_USERNAME: "appuser"
  SPRING_DATASOURCE_PASSWORD: "changeme"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"

