apiVersion: v1
kind: Service
metadata:
  name: demo-java
  namespace: demo-app
spec:
  type: ClusterIP
  selector:
    app: demo-java
  ports:
    - name: http
      port: 8080
      targetPort: http

