apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glowroot-central
  namespace: observability
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
    - host: glowroot.finchaokucoes.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: glowroot-central
                port:
                  name: ui
  tls:
    - hosts:
        - glowroot.finchaokucoes.com.br
      secretName: finch-tls-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: glowroot-cert
  namespace: observability
spec:
  secretName: glowroot-tls
  commonName: glowroot.finchaokucoes.com.br
  dnsNames:
    - glowroot.finchaokucoes.com.br
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer

